name: 'Tag Branch Action'
description: 'Create a tag in for new commit'
inputs:
  prefix:
    description: 'Prefix on tag'
    required: true
    default: "v"
  major:
    description: 'Major release version'
    required: true
  minor:
    description: 'Major release version'
    required: true
    default: 0
  token:
    description: 'The token to use to access the GitHub API'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'