name: 'test val replacement'
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      val:
        type: string
        description: Release tag, branch, commit
        default: support/v1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          val = github.event.inputs.ref
          echo "val1 : ${{ github.event.inputs.ref }}"

          
